export default Object.freeze({
    MAX_HARVESTERS: 3,
    MAX_BUILDERS: 1,
    MAX_UPGRADERS: 0,
    MAX_MOVERS: 1,
    MAX_REPAIRERS: 0,
    MAX_SCOUTS: 0,
    HARVESTER_BODY: [WORK, WORK, WORK, MOVE, MOVE, CARRY],
    UPGRADER_BODY: [WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, MOVE, MOVE, MOVE],
    REPAIRER_BODY: [WORK, WORK, WORK, CARRY, CARRY, MOVE, MOVE, MOVE],
    MOVER_BODY: [CARRY, MOVE],
    BUILDER_BODY: [WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE],
    SCOUT_BODY: [ATTACK, MOVE, MOVE]
});
